export const POST_NEW_TODO_REQ = "POST_NEW_TODO_REQ";
export const POST_NEW_TODO_RES = "POST_NEW_TODO_RES";
export const POST_NEW_TODO_ERROR = "POST_NEW_TODO_ERROR";

export const GET_ALL_TODOS_REQ = "GET_ALL_TODOS_REQ";
export const GET_ALL_TODOS_RES = "GET_ALL_TODOS_RES";
export const GET_ALL_TODOS_ERROR = "GET_ALL_TODOS_ERROR";

export const DELETE_TODO_REQ = "DELETE_TODO_REQ";
export const DELETE_TODO_RES = "DELETE_TODO_RES";
export const DELETE_TODO_ERROR = "DELETE_TODO_ERROR";

export const UPDATE_TODO_REQ = "UPDATE_TODO_REQ";
export const UPDATE_TODO_RES = "UPDATE_TODO_RES";
export const UPDATE_TODO_ERROR = "UPDATE_TODO_ERROR";